# Intro to NumPy

In [1]:
# Install NumPy if you haven't already
# !pip install numpy

# Import NumPy
import numpy as np

# Check NumPy version
print(f"NumPy version: {np.__version__}")

NumPy version: 2.0.2


# Creating NumPy Arrays

In [2]:
# Simple 1D array
arr1 = np.array([1, 2, 3, 4, 5])
arr1


array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
# 2D array (matrix)
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# 3D array (cube)
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
cube

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
mat.shape    # Size of each dimension

(3, 3)

In [7]:
mat.ndim     # Number of dimensions

2

In [8]:
mat.size     # Total number of elements

9

In [9]:
mat.dtype    # Data type of elements

dtype('int64')

# Array Creation Functions

In [10]:
zeros_array = np.zeros((3, 4))  # 3x4 array of zeros
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
ones_array = np.ones((2, 3))  # 2x3 array of ones
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
full_array = np.full((2, 2), 7)  # 2x2 array filled with 7
full_array

array([[7, 7],
       [7, 7]])

In [13]:
identity = np.eye(3)  # 3x3 identity matrix
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Create arrays with evenly spaced values
arange_array = np.arange(10)  # [0, 1, 2, ..., 9]
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# With start, stop, and step
arange_custom = np.arange(2, 20, 2)  # [2, 4, 6, ..., 18]
arange_custom

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced values from 0 to 1
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Random Number Generation

In [17]:
# Random floats in [0, 1)
rand = np.random.random((2, 2))
rand

array([[0.22946579, 0.67261796],
       [0.90675995, 0.86245836]])

In [18]:
# Random integers from 1 to 9
randint = np.random.randint(1, 10, size=(3, 3)) 
randint

array([[3, 2, 2],
       [9, 3, 5],
       [9, 7, 2]])

In [19]:
# Random values from a normal distribution
norm_arr = np.random.normal(0, 1, (2, 3))  # Mean=0, std=1
norm_arr

array([[ 0.27276734,  0.46118652, -1.42504057],
       [ 0.04997295, -0.33820414, -0.11008583]])

# Array reshaping and manipulation

In [20]:
# Create a 1D array
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
# Reshape to a 3x4 array
reshaped = a.reshape(3, 4)
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# Reshape to a 2x2x3 array
reshaped_3d = a.reshape(2, 2, 3)
reshaped_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [23]:
# Auto-calculate one dimension
auto = a.reshape(2, -1)  # 2 rows, columns calculated automatically
auto

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
# Make 1D again
flat = reshaped.flatten()
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
# Switch rows and columns
flipped = reshaped.T
flipped


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Indexing and Slicing

In [26]:
# Sample 2D array
grid = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
# Single element (row 1, column 2)
grid[1, 2]

np.int64(7)

In [28]:
# Entire row
grid[1]

array([5, 6, 7, 8])

In [29]:
# Entire column
grid[:, 2]

array([ 3,  7, 11])

In [30]:
# Subgrid (rows 0-1, columns 1-2)
grid[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [31]:
# Every other row and column
grid[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

In [32]:
# Last two rows, last two columns
grid[-2:, -2:]

array([[ 7,  8],
       [11, 12]])

# Basic Math Operations

In [33]:
# Simple arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [34]:
a + b      # Addition

array([5, 7, 9])

In [35]:
b - a      # Subtraction

array([3, 3, 3])

In [36]:
a * b      # Multiplication

array([ 4, 10, 18])

In [37]:
b / a      # Division

array([4. , 2.5, 2. ])

In [38]:
a ** 2     # Square

array([1, 4, 9])

### Trigonometry

In [39]:
angles = np.array([0, np.pi/4, np.pi/2, np.pi])
print("sin angle: ",np.sin(angles))
print("cos angle", np.cos(angles))

sin angle:  [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos angle [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]


### Statistics

In [40]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [41]:
np.mean(data)     # Average

np.float64(5.5)

In [42]:
np.median(data)   # Middle value

np.float64(5.5)

In [43]:
np.std(data)      # Standard deviation

np.float64(2.8722813232690143)

In [44]:
np.min(data)      # Minimum

np.int64(1)

In [45]:
np.max(data)      # Maximum

np.int64(10)

In [46]:
np.sum(data)      # Total

np.int64(55)

# Broadcasting (Different shaped arrays)

In [47]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [48]:
# Row operation (adds to each row)
b = np.array([10, 20, 30])
a + b

array([[11, 22, 33],
       [14, 25, 36]])

In [49]:
# Column operation (adds to each column)
c = np.array([[10], [20]])
a + c

array([[11, 12, 13],
       [24, 25, 26]])

# Matrix Operations

In [50]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [51]:
# Matrix multiplication
A @ B     # Same as np.matmul(A, B)


array([[19, 22],
       [43, 50]])

In [52]:
# Element multiplication
A * B

array([[ 5, 12],
       [21, 32]])

In [53]:
# Matrix determinant
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [54]:
# Matrix inverse
inv = np.linalg.inv(A)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [55]:
# Check inverse: A × A⁻¹ = I (identity)
A @ inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

# Solving Equations (Ax=b)

In [56]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

In [57]:
# Solve for x
x = np.linalg.solve(A, b)
x

array([2., 3.])

In [58]:
# Verify: A × x = b
A @ x

array([9., 8.])

# Boolean Indexing

In [59]:
arr = np.arange(1, 13).reshape(4, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
# Find values > 5
mask = arr > 5
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [61]:
# Get values where mask is True
arr[mask]

array([ 6,  7,  8,  9, 10, 11, 12])

In [62]:
# Combined conditions (5 < value < 10)
mask2 = (arr > 5) & (arr < 10)
arr[mask2]

array([6, 7, 8, 9])

In [63]:
# Select specific rows
rows = [0, 2, 3]  # First, third, and fourth rows
arr[rows]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

# Saving and Loading

In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
# Save binary file
np.save('myarray.npy', arr)

In [66]:
# Load binary file
loaded = np.load('myarray.npy')
loaded

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
# Save text file
np.savetxt('myarray.txt', arr, fmt='%d', delimiter=',')


In [68]:
# Load text file
txt = np.loadtxt('myarray.txt', delimiter=',')
txt

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])